config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'

  get '/about' => 'pages#about', as: 'about'


  resources :autos, only: [:show, :new, :create] do
    resources :contracts, only: [:index, :show]
  end

  resources :accident_contracts, only: [:new, :create]
  resources :health_requests, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/accident.rb
class Accident < ApplicationRecord
  has_many :coverages
  has_many :plans
end

app/models/accident_contract.rb
class AccidentContract < ApplicationRecord
  belongs_to :accident
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auto.rb
class Auto < ApplicationRecord
end

app/models/contract.rb
class Contract < ApplicationRecord
end

app/models/coverage.rb
class Coverage < ApplicationRecord
  belongs_to :accident, optional: true
  belongs_to :health_contract, optional: true
end

app/models/health_contract.rb
class HealthContract < ApplicationRecord
  has_many :coverages
  has_many :plans

  PRICE = {
    "Hombre":
    {
      "18": {basic: 18, dental: 1, life: 2},
      "19": {basic: 19, dental: 1, life: 2},
      "21": {basic: 21, dental: 1, life: 2},
      "22": {basic: 22, dental: 1, life: 2},
      "23": {basic: 23, dental: 1, life: 2},
      "24": {basic: 24, dental: 1, life: 2},
      "25": {basic: 25, dental: 1, life: 2},
      "26": {basic: 26, dental: 1, life: 2},
      "27": {basic: 27, dental: 1, life: 2},
      "28": {basic: 28, dental: 1, life: 2},
      },
      "Mujer":
      {
        "18": {basic: 18, dental: 1, life: 2},
        "19": {basic: 19, dental: 1, life: 2},
        "21": {basic: 21, dental: 1, life: 2},
        "22": {basic: 22, dental: 1, life: 2},
        "23": {basic: 23, dental: 1, life: 2},
        "24": {basic: 24, dental: 1, life: 2},
        "25": {basic: 25, dental: 1, life: 2},
        "26": {basic: 26, dental: 1, life: 2},
        "27": {basic: 27, dental: 1, life: 2},
        "28": {basic: 28, dental: 1, life: 2},
      }
    }


  end

app/models/health_request.rb
class HealthRequest < ApplicationRecord
  belongs_to :health_contract
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :accident, optional: true
  belongs_to :health_contract, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/accident_contracts_controller.rb
class AccidentContractsController < ApplicationController
  skip_before_action :authenticate_user!

  def new
    @accidentContract = AccidentContract.new()
  end

  def create
    @selectedPlan = params[:accident_id]
    @accidentContract = AccidentContract.new(accident_contract_params)
    @accidentContract.accident = Accident.find(@selectedPlan) unless @selectedPlan.blank?

    if @accidentContract && @accidentContract.accident.nil?
      contract_type = @accidentContract.contract_type
      @accidents = Accident.where("contract_type = ? AND min_age <= ? AND max_age >= ? ", contract_type, @accidentContract.age, @accidentContract.age)
      @min_coverage = {}
      @max_coverage = {}
      @accidents = @accidents.sort { |a,b| b.plans[0].annual_amount_cents <=> a.plans[0].annual_amount_cents }

      @accidents.each do |a|
        a.coverages.each do |c|
          # max
          if @max_coverage[c.coverage_type].nil?
            @max_coverage[c.coverage_type] = c.amount
          elsif c.amount > @max_coverage[c.coverage_type]
            @max_coverage[c.coverage_type] = c.amount
          end
        end
      end

      respond_to do |format|
        format.js {render "create"}
      end

    elsif @accidentContract.accident && @accidentContract.email.nil?
      respond_to do |format|
        format.js {render "userinfo.js.erb"}
      end

    elsif @accidentContract.email
      @accidentContract.save!
      redirect_to root_path
    end
  end

  # def filterContracts

  # end

  # def createProspect

  # end

  private

  def accident_contract_params
    params.require(:accident_contract).permit(:accident, :first_name, :last_name, :contract_type, :age, :gender, :email, :phone_number)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/autos_controller.rb
class AutosController < ApplicationController
  skip_before_action :authenticate_user!

  def show
    @auto = Auto.new()
  end

  def new
    @auto = Auto.new()
  end

  def create
    @auto = Auto.new(firstName: "NA", lastName: "NA", email:"na@na.com", autoBrand: "NA", autoModel:"NA", autoFeatures: "NA")
    # @auto = Auto.new(auto_params)
    # @auto.autoFeatures << params[:autoFeatures] unless params[:autoFeatures].blank?
    if @auto.save!
      redirect_to auto_contracts_path(@auto)
    else
      render :new
    end
  end

  private

  def auto_params
    params.permit(:firstName,
                   :lastName,
                   :email,
                   :autoBrand,
                   :autoModel,
                   :autoFeatures
                   )
  end

end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @contracts = Contract.all
  end

  def show
  end
end

app/controllers/health_requests_controller.rb
class HealthRequestsController < ApplicationController
  skip_before_action :authenticate_user!

  def new
    @health_request = HealthRequest.new()
  end

  def create
    @selectedPlan = params[:health_contract_id]
    puts params
    @health_request = HealthRequest.new(health_request_params)
    @health_request.health_contract = HealthContract.find(@selectedPlan) unless @selectedPlan.blank?

    if @health_request && @health_request.health_contract.nil?
      puts "*******Contract Screen********"
      gender = @health_request.gender
      @health_contracts = HealthContract.where("gender = ? AND min_age <= ? AND max_age >= ? ", gender, @health_request.age, @health_request.age)
      @min_coverage = {}
      @max_coverage = {}
      # @health_contracts = @health_contracts.sort { |a,b| b.plans[0].annual_amount_cents <=> a.plans[0].annual_amount_cents }

      @health_contracts.each do |a|
        a.coverages.each do |c|
          # max
          if @max_coverage[c.coverage_type].nil?
            @max_coverage[c.coverage_type] = c.amount
          elsif c.amount > @max_coverage[c.coverage_type]
            @max_coverage[c.coverage_type] = c.amount
          end
        end
      end

      respond_to do |format|
        format.js {render "create"}
      end

    elsif @health_request.health_contract && @health_request.email.nil?
      puts "*******User Screen********"
      respond_to do |format|
        format.js {render "userinfo.js.erb"}
      end

    elsif @health_request.email
      @health_request.save!
      redirect_to root_path
    end
  end

  private

  def health_request_params
    params.require(:health_request).permit(:health_contract, :first_name, :last_name, :age, :gender, :email, :phone_number, :dental, :life, :global)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :about]

  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accident_contracts/_accidents.html.erb
<h3>Tus Resultados:</h3>
<div class="fixed-action-btn direction-top active" style="bottom: 45px; right: 24px;">
  <a class="avatar-75" id="menu"><%= image_tag('Loguito-Zegurito.png') %></a>
</div>
  <div class="tap-target grey lighten-5" data-activates="menu">
    <div class="tap-target-content">
      <h4>Muerte Accidental y Desmembramiento</h4>
      <p>Esta cobertura lo protege contra dificultades financieras debidas a un accidente que causa la muerte, desmembramiento, parálisis, o pérdida de la vista, del habla o de audición.</p>
      <p>Necesitas mas Ayuda?</p>
    </div>
  </div>

<!-- logic for classyfying contracts -->
<% max_coverage.each {|k,v| highest_coverage += v} %>
<% accidents.each do |accident| %>
<% total_coverage = 0 %>
<% accident.coverages.each {|z| total_coverage += z.amount} %>
<% if ((total_coverage.to_f / highest_coverage.to_f) > 0.7)  %>
<% image_color = "green" %>
<% classification = "Máxima" %>
<% elsif ((total_coverage.to_f / highest_coverage.to_f) > 0.3) %>
<% image_color = "yellow" %>
<% classification = "Mediana" %>
<% else %>
<% image_color = "orange" %>
<% classification = "Baja" %>
<% end %>

<!-- cards -->
<div class="row">
  <!-- card -->
  <div class="col s12 m12">
    <%= form_with(model: @accidentContract) do |f| %>
    <%= f.hidden_field :contract_type, value: accidentContract.contract_type %>
    <%= f.hidden_field :age, value: accidentContract.age %>
    <%= hidden_field_tag 'accident_id', accident.id %>
    <div class="card">
      <!-- card header -->
      <div class="card-image">
        <%= image_tag("#{image_color}.png") %>
        <div class="card-title card-title-accident">
          <!-- Tipo de Cobertura Header -->
          <div>
            <p><strong><%= classification %></strong></p>
            <p><strong>Cobertura</strong></p>
          </div>
          <!-- Prima Mensula Header -->
          <div class="card-accident-header">
            <p class="card-price"><%= number_to_currency(accident.plans[0].amount_cents / 100, precision: 0) %></p>
            <p>Prima Mensual</p>
          </div>
        </div>
      </div>
      <!-- card content -->
      <div class="card-content">
        <p>Coberturas:</p>
        <% accident.coverages.where(important: true). each do |coverage| %>
        <!-- Element Showed -->
        <div class="progress" onclick="$('.tap-target').tapTarget('open')">
          <% coverage_percentage = (coverage.amount.to_f / max_coverage[coverage.coverage_type].to_f) * 100 %>
          <div class="determinate" style="width: <%= coverage_percentage %>%"></div>
          <p class="progress-text"><%= number_to_currency(coverage.amount, precision: 0) %> - <%= coverage.coverage_type %></p>
        </div>
        <% end %>
      </div>
      <div class="card-action">
        <button class="btn waves-light btn-brand-primary" type="submit" name="action">Aplicar</button>
        &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<a class="modal-trigger" href="#accidentmodal<%= accident.id %>">Detalles</a>
      </div>
      <%= render 'shared/accident-details-modal', accident: accident, classification: classification %>
    </div>
    <% end %>
  </div>
</div>
<% end %>

app/views/accident_contracts/_userinfo.html.erb
<h3 class="text-center">Último Paso!</h3>
<p class="text-center">Al llenar el formulario, uno de nuestros compañeros de Diamante Asesores se pondrá en contacto contigo para finalizar la subscripción</p>

<br>

<div class="row">
  <%= form_for accidentContract do |f| %>
  <%= f.hidden_field :contract_type, value: accidentContract.contract_type %>
  <%= f.hidden_field :age, value: accidentContract.age %>
  <%= hidden_field_tag 'accident_id', selectedPlan %>
  <div class="row">
    <div class="input-field col offset-m2 m8 s12">
      <%= f.text_field :first_name, wrapper_html: { class: 'offset-m2 m8 s12' } %>
      <%= f.label :first_name, "Cual es tu primer nombre?" %>
    </div>

    <div class="input-field col offset-m2 m8 s12">
      <%= f.text_field :last_name, wrapper_html: { class: 'offset-m2 m8 s12' } %>
      <%= f.label :last_name, "Cual es tu apellido?" %>
    </div>

    <div class="input-field col offset-m2 m8 s12">
      <%= f.text_field :email, wrapper_html: { class: 'offset-m2 m8 s12' } %>
      <%= f.label :email, "Cual es tu correo electronico?" %>
    </div>

    <div class="input-field col offset-m2 m8 s12">
      <%= f.text_field :phone_number, wrapper_html: { class: 'offset-m2 m8 s12' } %>
      <%= f.label :phone_number, "Cual es tu numero de teléfono?" %>
    </div>

    <div class="col s12 center-align">
      <button class="btn waves-light btn-brand-primary margin-top-50" type="submit" name="action">Cotizar
        <i class="material-icons right">send</i>
      </button>
    </div>
  </div>
  <% end %>
</div>


<%= content_for :after_js do %>
<script>
  $(document).ready(function() {
    Materialize.updateTextFields();
  });
</script>
<% end %>

app/views/accident_contracts/create.js.erb
$('.form-wrapper').empty();
formWrapper = document.querySelector('.form-wrapper');
formWrapper.className += " margin-top-20-vh";
formWrapper.insertAdjacentHTML('afterbegin', '<%= j render "accidents", accidentContract: @accidentContract, accidents: @accidents, max_coverage: @max_coverage, highest_coverage: 0 %>');
// $('.tap-target').tapTarget();
$('.modal').modal();
// $('.tap-target').tapTarget('open');

app/views/accident_contracts/new.html.erb
<% content_for :head_zoom do %>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1,user-scalable=0"/>
<% end %>

<div class="page-wrapper">
  <div class="form-banner"></div>
  <div class="form-wrapper">
    <%= render 'shared/accidentform' %>
  </div>
</div>

app/views/accident_contracts/userinfo.js.erb
$('.form-wrapper').empty();
formWrapper = document.querySelector('.form-wrapper');
formWrapper.className += " margin-top-20-vh";
formWrapper.insertAdjacentHTML('afterbegin', '<%= j render "userinfo", accidentContract: @accidentContract, selectedPlan: @selectedPlan %>');

app/views/autos/new.html.erb
<% content_for :head_zoom do %>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1,user-scalable=0"/>
<% end %>
<!-- <script type="text/javascript" src="https://cf-4053.kxcdn.com/conversational-form/0.9.6/conversational-form.min.js" crossorigin></script> -->

<div class="page-wrapper">
<div class="form-banner"></div>
  <div class="form-wrapper">
    <%= render 'shared/autoform' %>
  </div>
</div>

app/views/autos/show.html.erb
<h1>Autos#show</h1>
<p>Find me in app/views/autos/show.html.erb</p>

app/views/contracts/index.html.erb
<div class="cards-banner"></div>
<div class="page-wrapper">
  <div class="cards-header">
    <h2>Estos seguros encontramos para ti:</h2>
  </div>
  <div class="cards-wrapper">
    <div class="row">
      <%= render 'shared/contract-card' %>
      <%= render 'shared/contract-card' %>
      <%= render 'shared/contract-card' %>
      <%= render 'shared/contract-card' %>
    </div>
  </div>
</div>

app/views/contracts/show.html.erb
<h1>Contracts#show</h1>
<p>Find me in app/views/contracts/show.html.erb</p>

app/views/health_requests/_healthTypeform.html.erb
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
  <title>Seguro de salud</title>
  <style type="text/css"> html{ margin: 0; height: 100%; overflow: hidden; } iframe{ position: absolute; left:0; right:0; bottom:0; top:0; border:0; } </style>
</head>
<body>
  <iframe id="typeform-full" width="100%" height="100%" frameborder="0" src="https://zegurito.typeform.com/to/xP6Twy"></iframe> <script type="text/javascript" src="https://embed.typeform.com/embed.js">
</script>
</body>
</html>

app/views/health_requests/_healthcontracts.html.erb
<%= form_with(model: @health_request) do |f| %>
<%= f.hidden_field :gender, value: health_request.gender %>
<%= f.hidden_field :age, value: health_request.age %>
<%= f.hidden_field :global, value: true %>
<%= hidden_field_tag 'health_contract_id', health_contracts[0].id %>
<% hc = health_contracts.first %>
<% coverages = hc.coverages %>

<!-- Header with price -->

<div class="request-wrapper basic">
  <div class="price">
    <h3>$24/mes</h3>
    <p class="text-center">Seguro de salud</p>
  </div>
  <div class="basic-coverages">
    <h4>Coberturas en Centro America:</h4>
    <div class="row">
      <% hc.coverages.each do |c| %>
        <% if c.important %>
          <div class="col-xs-12 col-sm-6">
            <div class="coverage-white-box">
              <p>$<%= c.amount %> <%= c.coverage_type %></p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

</div>

<!-- <div class="request-wrapper global">
  <%= f.check_box :global, {class: "filled-in checkbox-brand-color", id: "global"}, "1", "0"%>
  <%= label_tag(:global, "Incluir cobertura global ($12/mes)") %>
</div> -->

<div class="request-wrapper dental">
  <div class="dental-coverages">
    <%= f.check_box :dental, {class: "filled-in checkbox-brand-color", id: "dental"}, "1", "0"%>
    <%= label_tag(:dental, "Plan dental ($6/mes)") %>
    <br>
    <div class="row">
      <div class="col-xs-12">
        <div class="coverage-primary-box">
         <% dental = coverages.where(coverage_type: "en cobertura dental anual") %>
          <p>$<%= dental[0].amount %> en cobertura dental</p>
        </div>
      </div>
      <div class="col-xs-12">
        <div class="coverage-primary-box">
        <% ortodoncia = coverages.where(coverage_type: "en cobertura de ortodoncia anual") %>
          <p>$<%= ortodoncia[0].amount %> en cobertura de ortodoncia</p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="request-wrapper life">
  <div class="life-coverages">
    <%= f.check_box :life, {class: "filled-in checkbox-brand-color", id: "life"}, "1", "0"%>
    <%= label_tag(:life, "Seguro de vida ($4/mes)") %>
    <br>
    <div class="row">
      <div class="col-xs-12">
        <div class="coverage-primary-box">
        <% vida = coverages.where(coverage_type: "Seguro de vida") %>
          <p>$<%= vida[0].amount %> en coberturas</p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="request-wrapper life">
  <button class="btn waves-light btn-brand-primary" type="submit" name="action">Aplicar</button>
</div>

<% end %>

<!-- <div class="fixed-action-btn direction-top active" style="bottom: 45px; right: 24px;">
  <a class="avatar-75" id="menu"><%= image_tag('Loguito-Zegurito.png') %></a>
</div> -->

app/views/health_requests/_healthinsurance.html.erb
<h3>Tus Resultados:</h3>
<div class="fixed-action-btn direction-top active" style="bottom: 45px; right: 24px;">
  <a class="avatar-75" id="menu"><%= image_tag('Loguito-Zegurito.png') %></a>
</div>
  <div class="tap-target grey lighten-5" data-activates="menu">
    <div class="tap-target-content">
      <h4>Muerte Accidental y Desmembramiento</h4>
      <p>Esta cobertura lo protege contra dificultades financieras debidas a un accidente que causa la muerte, desmembramiento, parálisis, o pérdida de la vista, del habla o de audición.</p>
      <p>Necesitas mas Ayuda?</p>
    </div>
  </div>

<!-- logic for classyfying contracts -->
<% max_coverage.each {|k,v| highest_coverage += v} %>
<% health_contracts.each do |health_contract| %>
<% total_coverage = 0 %>
<% health_contract.coverages.each {|z| total_coverage += z.amount} %>
<% if ((total_coverage.to_f / highest_coverage.to_f) > 0.9)  %>
<% image_color = "green" %>
<% classification = "Máxima" %>
<% elsif ((total_coverage.to_f / highest_coverage.to_f) > 0.3) %>
<% image_color = "yellow" %>
<% classification = "Mediana" %>
<% else %>
<% image_color = "orange" %>
<% classification = "Baja" %>
<% end %>

<!-- cards -->
<div class="row">
  <!-- card -->
  <div class="col s12 m12">
    <%= form_with(model: @health_request) do |f| %>
    <%= f.hidden_field :gender, value: health_request.gender %>
    <%= f.hidden_field :age, value: health_request.age %>
    <%= hidden_field_tag 'health_contract_id', health_contract.id %>
    <div class="card">
      <!-- card header -->
      <div class="card-image">
        <%= image_tag("#{image_color}.png") %>
        <div class="card-title card-title-accident">
          <!-- Tipo de Cobertura Header -->
          <div>
            <p><strong><%= classification %></strong></p>
            <p><strong>Cobertura</strong></p>
          </div>
          <!-- Prima Mensula Header -->
          <div class="card-accident-header">
            <p class="card-price"><%= number_to_currency(health_contract.plans[0].amount_cents / 100, precision: 0) %></p>
            <p>Prima Mensual</p>
          </div>
        </div>
      </div>
      <!-- card content -->
      <div class="card-content">
        <p>Coberturas:</p>
        <% health_contract.coverages.where(important: true). each do |coverage| %>
        <!-- Element Showed -->
        <div class="progress" onclick="$('.tap-target').tapTarget('open')">
          <% coverage_percentage = (coverage.amount.to_f / max_coverage[coverage.coverage_type].to_f) * 100 %>
          <div class="determinate" style="width: <%= coverage_percentage %>%"></div>
          <p class="progress-text"><%= number_to_currency(coverage.amount, precision: 0) %> - <%= coverage.coverage_type %></p>
        </div>
        <% end %>
      </div>
      <div class="card-action">
        <button class="btn waves-light btn-brand-primary" type="submit" name="action">Aplicar</button>
        &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<a class="modal-trigger" href="#health-contract-modal<%= health_contract.id %>">Detalles</a>
      </div>
      <%= render 'shared/health-contract-modal', health_contract: health_contract, classification: classification %>
    </div>
    <% end %>
  </div>
</div>
<% end %>

app/views/health_requests/_userinfo.html.erb
<div class="form-wrapper margin-top-10-vh">
  <h3 class="text-center">Último Paso!</h3>
  <p class="text-center">Al llenar el formulario, uno de nuestros compañeros de Diamante Asesores se pondrá en contacto contigo para finalizar la subscripción</p>

  <br>

  <div class="row">
    <%= form_for health_request do |f| %>
    <%= f.hidden_field :gender, value: health_request.gender %>
    <%= f.hidden_field :age, value: health_request.age %>
    <%= hidden_field_tag 'health_contract_id', selectedPlan %>
    <div class="row">
      <div class="input-field col offset-m2 m8 s12">
        <%= f.text_field :first_name, wrapper_html: { class: 'offset-m2 m8 s12' } %>
        <%= f.label :first_name, "Cual es tu primer nombre?" %>
      </div>

      <div class="input-field col offset-m2 m8 s12">
        <%= f.text_field :last_name, wrapper_html: { class: 'offset-m2 m8 s12' } %>
        <%= f.label :last_name, "Cual es tu apellido?" %>
      </div>

      <div class="input-field col offset-m2 m8 s12">
        <%= f.text_field :email, wrapper_html: { class: 'offset-m2 m8 s12' } %>
        <%= f.label :email, "Cual es tu correo electronico?" %>
      </div>
<!--
      <div class="input-field col offset-m2 m8 s12">
        <%= f.text_field :phone_number, wrapper_html: { class: 'offset-m2 m8 s12' } %>
        <%= f.label :phone_number, "Cual es tu numero de teléfono?" %>
      </div> -->

      <div class="col s12 center-align">
        <button class="btn waves-light btn-brand-primary margin-top-50" type="submit" name="action">Finalizar
          <i class="material-icons right">send</i>
        </button>
      </div>
    </div>
    <% end %>
  </div>
</div>


<%= content_for :after_js do %>
<script>
  $(document).ready(function() {
    Materialize.updateTextFields();
  });
</script>
<% end %>

app/views/health_requests/create.js.erb
$('.page-wrapper').empty();
pageWrapper = document.querySelector('.page-wrapper');
pageWrapper.insertAdjacentHTML('afterbegin', '<%= j render "healthcontracts", health_request: @health_request, health_contracts: @health_contracts, max_coverage: @max_coverage, highest_coverage: 0 %>');
$('.modal').modal();
// $('.tap-target').tapTarget();
// $('.tap-target').tapTarget('open');

app/views/pages/home.html.erb
<div class="homepage-wrapper" style="background-image: url('<%= image_url('bg-zegurito.jpg') %>'); background-position: center;">

  <div class="homepage-content">
    <a class="avatar-150" id="menu"><%= image_tag('Loguito-Zegurito.png') %></a>
    <h1>Escoge seguros en minutos</h1>
    <h4>Zegurito, nuestro experto, te ayudará en el proceso</h4>
    <br><br>

 <!--     Button for car insurance
    <%= link_to new_auto_path, class: "waves-effect btn-large btn-brand-secondary" do %>
      <div class="icon-btn-wrapper">
        <i class="large material-icons two-rem-icon">directions_car</i>
        <span>&nbsp&nbspSeguro de automovil&nbsp&nbsp</span>
      </div>
    <% end %>
    <br><br> -->
    <!-- Button for Home insurance -->
    <%= link_to new_health_request_path, class: "waves-effect btn-large btn-brand-primary" do %>
      <div class="icon-btn-wrapper">
        <i class="large material-icons two-rem-icon">local_hospital</i>
        <span>&nbsp&nbspSeguro de salud&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</span>
      </div>
    <% end %>
    <br>
    <br>
<!--     <%= link_to new_accident_contract_path, class: "waves-effect btn-large btn-brand-primary" do %>
      <div class="icon-btn-wrapper">
        <i class="large material-icons two-rem-icon">report</i>
        <span>&nbsp&nbspSeguro de accidentes</span>
      </div>
    <% end %> -->
    <br>
    <br>
    <br>
  </div>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag("zegurito-logo.png"); %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Links when logged in -->
    <!-- <%= link_to "SEGUROS", new_auto_path, class: "navbar-wagon-item navbar-wagon-link" %> -->
    <%= link_to "QUIENES SOMOS", about_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "CONTÁCTANOS", "#", class: "navbar-wagon-item navbar-wagon-link" %>
    <% if user_signed_in? %>
    <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>

  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>